version: '2'
services:
  nginx:
    image: hoangstark/bedrock-nginx:latest
    ports:
     - "8080:80"
    volumes:
     - ./.development/site:/usr/share/nginx/html
    networks:
     - wpnet
  php:
    image: hoangstark/bedrock-php:latest
    volumes:
     - ./.development/site:/usr/share/nginx/html
     - ./plugin:/usr/share/nginx/html/web/app/plugins/plugin-dev
    networks:
     - wpnet
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
    volumes:
     - ./.development/data:/var/lib/mysql
    networks:
     - wpnet
networks:
  wpnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"